version: 0.2

cache:
  paths:
    - node_modules/**/*
    - /root/.npm/**/*

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --include=dev
  build:
    commands:
      - printenv | grep NODE
      - npm run build
      - printenv | grep NODE
  post_build:
    commands:
      - echo Build completed on `date`
      - find . -type d -name node_modules -prune -o -path ./cypress -prune -o -path ./.nx -prune -o -name '*' -print
      # Copy build output directory to CodePipeline artifact location
      - find / -type f -name *decap-cms.js
      - aws s3 sync packages/decap-cms/dist s3://decapdeployartifact --delete
      - aws cloudfront create-invalidation --distribution-id E2ESIHMO0F0F37 --paths "/*"

artifacts:
  files:
    - packages/decap-cms/dist/*
  base-directory: packages/decap-cms/dist

